#page title
page_title: # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id: 1486204851 # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country: de # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link: # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link: https://play.google.com/ # Enter Google Play Store URL.
presskit_download_link:
  # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon: # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price: # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description: Dein persönlicher Manga Manager.

enable_smart_app_banner: true # Set to true to show a smart app banner at top of page on mobile devices.

# Information About Yourself
your_name: DeltaSiege
your_link: https://deltasiege.ddnss.eu
email_address: dominic.drees@live.de
facebook_username:
instagram_username:
twitter_username: DominicDrees
github_username: undeaDD
youtube_username:

# Feature List                            Edit, add or remove features to be presented.
features:
  - title: Mangas Verwalten
    description: Verwalte ganz einfach deine Mangas durch wenige Klicks. Qualität, Preis, Kaufdatum, Duplikate und vieles mehr.
    fontawesome_icon_name: book

  - title: Merkliste
    description: Fülle deine Sammlung jetzt noch einfacher, ohne das lästige rätseln und erinnern welcher Band noch fehlt.
    fontawesome_icon_name: book-bookmark

  - title: Erkunden
    description: Mit mehr als 5000 Mangas sollte für jeden etwas dabei sein. Es gibt außerdem die Möglichkeit Zufällige Mangas auszuwählen.
    fontawesome_icon_name: magnifying-glass

  - title: Freunde finden
    description: Freunde ganz bequem via E-Mail hinzufügen. Ganz praktisch wenn man sich gegenseitig Mangas schenkt / kauft und wissen will welche noch gewünscht sind.
    fontawesome_icon_name: user-group

  - title: Animationen
    description: Jede Saison hat ihre eigene schöne Animation ^^ Einfach mal ausprobieren und genießen.
    fontawesome_icon_name: wand-magic-sparkles

  - title: Dark Mode
    description: Für alle die gerne Abends lesen und ihre Sammlung einsehen wollen. Augenschmerzen nein danke.
    fontawesome_icon_name: moon

  - title: Übersicht behalten
    description: "Jederzeit und überall auf die eigene Sammlung zugreifen können. Fragen wie: 'Welcher Teil von Black Bird fehlt mir noch?' gehören mit Korekushon der Vergangenheit an."
    fontawesome_icon_name: eye

  - title: Support & Updates
    description: Bei Fragen oder Wünschen ( Features, Bugs, ... ) einfach via App ein Feedback absenden. Oder alternativ für Fortgeschrittene in github eine neue Issue eröffnen.
    fontawesome_icon_name: pen-to-square

  - title: Integrationen
    description: Details von Mangas werden direkt von Mangaguide.de abgerufen. Der Thalia Tab ermöglicht das schnelle Bestellen von Mangas direkt aus der App.
    fontawesome_icon_name: earth-europe

  - title: Danksagung
    description: Seraine, Sayonee, xDaarJR, Darkfinst, ...
    fontawesome_icon_name: medal

# Theme Settings
topbar_color: "#000000"
topbar_transparency: 0.1
topbar_title_color: "#ffffff"

cover_image: assets/headerimage.png
cover_overlay_color: "#363b3d"
cover_overlay_transparency: 0.8

device_color: white

body_background_color: "#ffffff"

link_color: "#1d63ea"

app_title_color: "#ffffff"
app_price_color: "#ffffff"
app_description_color: "#ffffff"

feature_title_color: "#000000"
feature_text_color: "#666666"

feature_icons_foreground_color: "#1d63ea"
feature_icons_background_color: "#e6e6e6"

social_icons_foreground_color: "#666666"
social_icons_background_color: "#e6e6e6"

footer_text_color: "#666666"

####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
